### ISSUE TITLE
Calculators: Forgiveness comparison and Income Driven Repayment Comparison

### ISSUE THREAD

**Issue by brandonyahn** [cuzzo/rtr#4]
They should each be able to be embedded on the rec tool landing pages and as a standalone on any page.
These formulas are more complex that using a basic math formula - e.g. they involve lookups from tables and more complicated math formulas. We should discuss how to make this easiest for coding - whether looking up and pulling from a stored table or trying to combine math formulas with some sort of lookup. See "Calculators" tab in Google doc: https://docs.google.com/spreadsheets/d/1JRDAD5264cio_vpyWP4B7SedYuih74Gvxwe4S-EhZCw/edit#gid=424368771

1. Public Service Loan Forgiveness calculator:
example: https://studentloanhero.com/calculators/public-service-loan-forgiveness-calculator/
each of these options have a slightly different formula - find the details on my site: https://www.rolltoriches.com/income-based-repayment/

2. Income-Driven Repayment comparison calculator:
example: https://studentloanhero.com/calculators/student-loan-income-based-repayment-calculator/

For the rec tool: The forgiveness calculator would be shown on scenario output #3 and the income driven calculator comparison would be shown in scenario output #4.

**Comment by cuzzo** [comment]
@brandonyahn For the Income-Based Repayment calculator, I see this in excel: (A$40-IF(A$43="AK",VLOOKUP(U$7,$T$33:$W$40,4,0),IF(U$8="HI",VLOOKUP(U$7,$T$33:$W$40,3,0),VLOOKUP(U$7,$T$33:$W$40,2,0))))*IF(A$44="Yes",U$26,U$28)/12 . I'm not too familiar with excel to really know what that means, though |=

It looks pretty straightforward, though. It seems like:

* If state == Alaska, do something
* If state == Hawaii, do something
* else, do something

Looks like "do something" is a function of family size, interest rate, if your loan was before 2014, and annual income? I'm pretty clueless how it uses those variables to make the calculation, though.

**Comment by brandonyahn** [comment]
Yes, for both the Income Driven Repayment and the Public Service Loans Forgiveness calculators, there are 3 options (Income-based repayment, Pay as You Earn, and Revised Pay as Your Earn) + a comparison to what a person would pay if they stuck to the Standard Plan.

The Public Service Loan Forgiveness comparison calculator will forgive loans after 120 payments (10 years), so a person would want to compare the total amount they would pay and the amount forgiven for each plan to determine which one to choose.

The Income Driven Repayment comparison calculator will forgive loans after 20-25 years of payments (depending on the plan, and assuming that they don't pay off all of the loans by that point in time). A person with relatively low income would want to compare the total amount they would pay and the amount forgiven for each plan to determine which one to choose.

These all use a lot of the same logic, but have slight difference based on how you answer a few of these questions. For example:

The inputs would be:
[__#__] Student Loan Balance
[__#__] Annual Interest Rate
[__#__] Annual Adjusted Gross Income
[__#__] Annual Income Growth
[__#__] Family Size - choose from drop down of "1,2,3,4,5,6,7,8"
[__text__] State - choose from drop down of "lower 48 states, Alaska, Hawaii"
[__test__] Was your first loan before July 1, 2104? - choose from drop down of "yes, no"
- I have a question about grad school yes/no, but that doesn't need to be included

For logic:
Family Size and State answers would need to be matched up against a table to determine a person's disposable income, which is used to calculate what their monthly payment amount would be.

The table is:
Fam   48 states	HI	AK
1	 17,820 	 22,260 	 20,505 
2	 24,030 	 30,030 	 27,645 
3	 30,240 	 37,800 	 34,785 
4	 36,450 	 45,570 	 41,925 
5	 42,660 	 53,340 	 49,065 
6	 48,870 	 61,110 	 56,205 
7	 55,095 	 68,880 	 63,345 
8	 61,335 	 76,680 	 70,515 

The monthly payment amount would then be determined by subtracting this number from the table by the "Adjusted Annual Gross Income" that was initially input, and multiplying that by either 10% or 15% (based on yes/no if the loan was "before July 1, 2014) and dividing by 12 to get monthly payment for income-based repayment.  For Pay as You Earn and Revised Pay As Your Earn, it would follow the same logic, except the monthly payment amount would be 10% in either circumstance. 

The monthly payment amount could change each year based on that person's income growth. So this would need to be calculated each year, then summed up to determine the person's total payments and total amount to be forgiven after 10 years in the Public Service Loan Forgiveness plan or 20 to 25 years in the IBR, PAYE, RePAYE plans. The standard plan comparison can easily be calculated using the basic "Payment Calculator" formulas.

These formulas can get pretty tricky as it has to read from different parts of the table based on how the income grows, sum of monthly payments, interest, etc. over time. I'm not sure if it's easier to try to come up with formulas that can try to cover all of this or if it's possible for these numbers to sit in a table and update and by read/pulled from there. Let me know what's easier for you and how I can help on this.

**Comment by brandonyahn** [comment]
For example:
(A$40-IF(A$43="AK",VLOOKUP(U$7,$T$33:$W$40,4,0),IF(U$8="HI",VLOOKUP(U$7,$T$33:$W$40,3,0),VLOOKUP(U$7,$T$33:$W$40,2,0))))*IF(A$44="Yes",U$26,U$28)/12 .
means:

1. Annual Adjusted Gross Income (data input, e.g. $60,000) 
-(SUBTRACT)
2. IF State = "Alaska" (or Hawaii, lower 48 states) AND Family Size = "1" (or 2,3,4,5,6,7,8),
 THEN lookup value from the table ($20,505)
= $39,495
3. *(MULTIPLY)
IF "Loan was before July 1, 2014" = **Yes** or No
 THEN 10% or **15%**
4. / DIVIDE BY 12 (for monthly payment)
= $493.69

This would be the monthly payment for the first year. Income could change each year, so this would change the monthly payments each year, as well as the sum of the total payments and forgiveness amount over 120 periods (10 years) or up to 300 periods (25 years).

**Comment by brandonyahn** [comment]
See sketch for scenario output #3 - Forgiveness
![output 3 - forgive](https://cloud.githubusercontent.com/assets/24615488/21667587/298fb4e6-d2af-11e6-90b8-97ca0fa90c5d.JPG)

and for scenario #4 - Income Driven Repayment
![output 4 - income driven](https://cloud.githubusercontent.com/assets/24615488/21667590/2f1175a8-d2af-11e6-9ca4-44c490764da2.JPG)
