### ISSUE TITLE
Loan calculations are incorrect.

### ISSUE THREAD

**Issue by cuzzo** [cuzzo/rtr#9]
The total payments and monthly payments calculated on the refinance page are incorrect.

**Comment by cuzzo** [comment]
@brandonyahn This should be roughly correct now. It's not compounding daily, but the difference is pretty trivial. Let me know are still outside an acceptable margin of error, and I'll close this issue. Thanks!

**Comment by brandonyahn** [comment]
I just went through the flow on example.html and it looks like the calculator is no longer there. How do I check this?
